version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "mwitasse"
  # Check for Docker image updates
  - package-ecosystem: "docker"
    directory: "/caddy-netcup-duckdns-ddns-ratelimit-dockerproxy"
    schedule:
      interval: "daily"
    assignees:
      - "mwitasse"
